### ISSUE TITLE
website is down!

### ISSUE THREAD

**Issue by Foadsf** [diogocabral/sherlock#1]
your website is down!

**Comment by diogocabral** [comment]
It's the author's website, not mine. However, I got the old content from google cache and append to README.md, I also got the original implementation of sig.c and comp.c. Take a look now.

**Comment by Foadsf** [comment]
A ok. Thanks for the reply. I mentioned your repo [here in this Reddit post](https://www.reddit.com/r/opensource/comments/8xgldr/any_freeopensource_software_for_plagiarism/). Feel free to join and share your experience.

**Comment by Foadsf** [comment]
[This page from University of Warwick](https://warwick.ac.uk/fac/sci/dcs/research/ias/software/sherlock/) gives [a java program](https://warwick.ac.uk/fac/sci/dcs/research/ias/software/sherlock/sherlocksource.zip) but here you have a C program. are these the same or I'm missing something here?

**Comment by diogocabral** [comment]
C implementation is the original, new improvements have been made in Java.

I recomend you to check these tools: MOSS and JPlag. I got the best results with those two.

[MOSS](https://theory.stanford.edu/~aiken/moss/)
[JPlag](https://github.com/jplag/jplag)

**Comment by Foadsf** [comment]
Hadn't heard of JPlag before. MOSS doesn't seem to be open source, is it though?

**Comment by diogocabral** [comment]
Yeah, you are right.  MOSS isn't open source. 

All I know is: MOSS it is based on Winnowing algorithms, at least the original version. 
JPlag used to be proprietary also, but thankfully they changed their mind. For more information, you can check the articles below.

[Finding Plagiarisms among a Set of Programs with JPlag](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.15.2990)
[Winnowing: local algorithms for document fingerprinting](https://dl.acm.org/citation.cfm?doid=872757.872770)

**Comment by Foadsf** [comment]
In [this reddit post](https://www.reddit.com/r/opensource/comments/8xgldr/any_freeopensource_software_for_plagiarism/) I'm trying to gather all the available free and open source projects. It is a shame that we still don't have anything reliable. maybe joining forces can help.
