### ISSUE TITLE
Empty Result

### ISSUE THREAD

**Issue by pravinprabhu** [diogocabral/sherlock#3]
./sherlock *.java > results.txt

i am trying to compare two java files...but the result is empty...

**Comment by diogocabral** [comment]
Try ./sherlock -e .java -r ~/my_java_code_dir/ > results.txt

**Comment by metalhacker** [comment]
Hi friend, I am facing with the same situation. When I type `./sherlock *.cpp` it just give no output. I have also tried your method and it seems that the dir was not sccessfully created (however simply use `./sherlock *.cpp > result.txt` will have the txt file created but empty). 
I'm not quite sure if it there's somthing wrong during the compilation? I cannot complie it by `make` and it throws and error saying DT_REG is not declared, but I compiled it successfully by simply `gcc sherlock.cpp -o sherlock` and the program is runable, just no output.

**Comment by pravinprabhu** [comment]
i tried the command suggested by @diogocabral .... it's working fine

**Comment by diogocabral** [comment]
> Hi friend, I am facing with the same situation. When I type `./sherlock *.cpp` it just give no output. I have also tried your method and it seems that the dir was not sccessfully created (however simply use `./sherlock *.cpp > result.txt` will have the txt file created but empty).
> I'm not quite sure if it there's somthing wrong during the compilation? I cannot complie it by `make` and it throws and error saying DT_REG is not declared, but I compiled it successfully by simply `gcc sherlock.cpp -o sherlock` and the program is runable, just no output.

Try ./sherlock -e .cpp -r ~/code_dir/ > results.txt
