### ISSUE TITLE
zsh: command not found: sherlock

### ISSUE THREAD

**Issue by chasmani** [diogocabral/sherlock#9]
Hi, thanks for this contribution. However, I'm having trouble getting started. 

I followed your instructions on the README. I downloaded the repo, unzipped it, ran 'make' from the unziped directory. When I then type the command 'sherlock' I get

zsh: command not found: sherlock

I also tried running it like ./sherlock but it does not give any output

I'm not super familiar with how to run or make these kinds of files. Any cahnce you could send more detailed instructions or update the README? 
Thank you, Charlie

**Comment by chasmani** [comment]
I got it to work like this

./sherlock -e .py *

(I am checking python files in a subdirectory). 

Could I suggest that you improve the README? 

1. Maybe say that users might need to use ./sherlock
2. The examples that you give, e.g. 'sherlock *.txt' don't actually work, because the fileextension is still set to the default of .c. To compare txt files the command would be './sherlock -e .txt *', and the txt files would need to be a subdirectory. 

I would make a pull request myself but I don't really know what I'm doing with running comiled c packagaes etc.

**Comment by diogocabral** [comment]
Hi, @chasmani 
Could you create a pull request?

**Comment by rodoac89** [comment]
I will edit the Readme file, thanks @chasmani
